SELECT *
FROM 	PORTFOLIOPROJECT..COVIDDEATHS_CLEAN
WHERE CONTINENT IS NOT NULL
ORDER BY 3, 4;


-- LIKELIHOOD OF DYING IF YOU CONTRACT COVID IN YOUR COUNTRY
SELECT
	LOCATION,
	DATE,
	TOTAL_CASES,
	TOTAL_DEATHS, 
	(TOTAL_DEATHS) / (TOTAL_CASES)*100 AS DEATHPERCENTAGE 
FROM
	PORTFOLIOPROJECT..COVIDDEATHS_CLEAN
--- WHERE LOCATION LIKE '%SRI%' 
ORDER BY 1, 2 DESC;

--TOTAL CASES VS POPULATION
-- SHOWS WHAT % OF POPULATION GOT COVID.
SELECT 
	LOCATION,
	DATE,
	POPULATION,
	TOTAL_CASES,
	TOTAL_DEATHS,
	(TOTAL_DEATHS/NULLIF(TOTAL_CASES,0))*100 AS PERCENTPOPULATIONINFECTED
FROM PORTFOLIOPROJECT..COVIDDEATHS_CLEAN
ORDER BY 1, 2;

-- COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION
SELECT 
	LOCATION, 
	POPULATION, 
	MAX(TOTAL_CASES) AS HIGHESTINFECTIONCOUNT,
	MAX((TOTAL_CASES/NULLIF(POPULATION, 0)))*100 AS PERCENTPOPULATIONINFECTED
FROM PORTFOLIOPROJECT..COVIDDEATHS_CLEAN
GROUP BY LOCATION, POPULATION
ORDER BY PERCENTPOPULATIONINFECTED DESC;

-- COUNTRIES WITH HIGHEST DEATHS PER POPULATION
SELECT 
    LOCATION, 
    MAX(TOTAL_DEATHS) AS TOTALDEATHS
FROM PORTFOLIOPROJECT..COVIDDEATHS_CLEAN
WHERE 
    CONTINENT IS NOT NULL
    AND LOCATION NOT IN (
        'WORLD',
        'EUROPEAN UNION',
        'INTERNATIONAL',
        'HIGH INCOME',
        'UPPER MIDDLE INCOME',
        'LOWER MIDDLE INCOME',
        'LOW INCOME',
        'AFRICA',
        'ASIA',
        'EUROPE',
        'NORTH AMERICA',
        'SOUTH AMERICA',
        'OCEANIA'
    )
GROUP BY LOCATION
ORDER BY TOTALDEATHS DESC;

-- TOTAL DEATHS BY CONTINENT
SELECT
    CONTINENT,
    MAX(TOTAL_DEATHS) AS TOTALDEATHSBYCONTINENT
FROM PORTFOLIOPROJECT..COVIDDEATHS_CLEAN
WHERE 
    CONTINENT IS NOT NULL
    AND CONTINENT <> ''
    AND LOCATION NOT IN ('WORLD', 'EUROPEAN UNION', 'INTERNATIONAL')
GROUP BY CONTINENT
ORDER BY TOTALDEATHSBYCONTINENT DESC;

-- GLOBAL NUMBERS
SELECT
    SUM(NEW_CASES) AS TOTAL_CASES,
    SUM(NEW_DEATHS) AS TOTAL_DEATHS,
    SUM(NEW_DEATHS)/SUM(NULLIF(NEW_CASES, 0)) * 100 AS DEATHPERCENTAGE
FROM PORTFOLIOPROJECT..COVIDDEATHS_CLEAN
--GROUP BY DATE
ORDER BY 1, 2; 


SELECT 
    DEA.CONTINENT,
    DEA.LOCATION,
    DEA.DATE,
    DEA.POPULATION,
    VAC.NEW_VACCINATIONS,
    SUM(CAST(VAC.NEW_VACCINATIONS AS INT))
    OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
    AS TOTALVACCINATEDBYLOC
FROM 
    PORTFOLIOPROJECT..COVIDDEATHS_CLEAN DEA
    JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
    ON DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
    AND DEA.CONTINENT <> ''
    AND DEA.LOCATION NOT IN ('WORLD', 'EUROPEAN UNION', 'INTERNATIONAL')
-- ORDER BY 2,3;


-- USE CTE

WITH POPULATIONVSVACCINE 
    (CONTINENT,LOCATION, DATE, POPULATION, NEW_VACCINATIONS, TOTALVACCINATEDBYLOC) AS
(
SELECT 
    DEA.CONTINENT,
    DEA.LOCATION,
    DEA.DATE,
    DEA.POPULATION,
    VAC.NEW_VACCINATIONS,
    SUM(CAST(VAC.NEW_VACCINATIONS AS INT))
    OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
    AS TOTALVACCINATEDBYLOC
FROM 
    PORTFOLIOPROJECT..COVIDDEATHS_CLEAN DEA
    JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
    ON DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
    AND DEA.CONTINENT <> ''
    AND DEA.LOCATION NOT IN ('WORLD', 'EUROPEAN UNION', 'INTERNATIONAL')
-- ORDER BY 2,3;
)
SELECT *, (TOTALVACCINATEDBYLOC/NULLIF(POPULATION, 0))*100
FROM POPULATIONVSVACCINE;


-- TEMP TABLE

DROP TABLE IF EXISTS #PERCENTPOPULATIONVACCINATED
CREATE TABLE #PERCENTPOPULATIONVACCINATED
(
CONTINENT NVARCHAR(255),
LOCATION NVARCHAR(255),
DATE DATETIME,
POPULATION NUMERIC,
NEW_VACCINATIONS NUMERIC,
TOTALVACCINATEDBYLOC NUMERIC
)

INSERT INTO #PERCENTPOPULATIONVACCINATED
SELECT 
    DEA.CONTINENT,
    DEA.LOCATION,
    DEA.DATE,
    TRY_CAST(DEA.POPULATION AS NUMERIC),
    TRY_CAST(VAC.NEW_VACCINATIONS AS NUMERIC),
    SUM(CAST(VAC.NEW_VACCINATIONS AS INT))
    OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
    AS TOTALVACCINATEDBYLOC
FROM 
    PORTFOLIOPROJECT..COVIDDEATHS_CLEAN DEA
    JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
    ON DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.DATE
-- WHERE DEA.CONTINENT IS NOT NULL
    AND DEA.CONTINENT <> ''
    AND DEA.LOCATION NOT IN ('WORLD', 'EUROPEAN UNION', 'INTERNATIONAL')
-- ORDER BY 2,3;

SELECT *, (TOTALVACCINATEDBYLOC/NULLIF(POPULATION, 0))*100
FROM #PERCENTPOPULATIONVACCINATED;



-- CREATE VIEW FOR LATER
CREATE VIEW PERCENTPOPULATIONVACCIned AS
SELECT 
    DEA.CONTINENT,
    DEA.LOCATION,
    DEA.DATE,
    TRY_CAST(DEA.POPULATION AS NUMERIC) POPULATION, 
    TRY_CAST(VAC.NEW_VACCINATIONS AS NUMERIC) NEW_VACCINATIONS,
    SUM(CAST(VAC.NEW_VACCINATIONS AS INT))
    OVER (PARTITION BY DEA.LOCATION ORDER BY DEA.LOCATION, DEA.DATE)
    AS TOTALVACCINATEDBYLOC
FROM 
    PORTFOLIOPROJECT..COVIDDEATHS_CLEAN DEA
    JOIN PORTFOLIOPROJECT..COVIDVACCINATIONS VAC
    ON DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
    AND DEA.CONTINENT <> ''
    AND DEA.LOCATION NOT IN ('WORLD', 'EUROPEAN UNION', 'INTERNATIONAL')
-- ORDER BY 2,3;

